name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Ручной запуск через интерфейс
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false

jobs:
  test-lint-security:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8 bandit

      # Шаг 4: Запуск тестов и проверка покрытия
      - name: Run tests with coverage
        run: |
          pytest --cov=discriminant --cov-report=xml

      # Шаг 5: Линтинг кода
      - name: Lint code with flake8
        run: flake8 discriminant.py test_discriminant.py

      # Шаг 6: Проверка безопасности
      - name: Security check with Bandit
        run: bandit -r .

  notify-telegram:
    runs-on: ubuntu-latest
    needs: test-lint-security
    steps:
      - name: Send Telegram notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="✅ Пайплайн завершился успешно!"
          else
            STATUS="❌ Пайплайн завершился неудачно!"
          fi
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"$CHAT_ID\", \"text\": \"$STATUS\"}" \
            https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage
